language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t 100121144d/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true 100121144d/react-test npm test -- --coverage

after_success:
    - docker build -t 100121144d/multi-client ./client
    - docker build -t 100121144d/multi-nginx ./nginx
    - docker build -t 100121144d/multi-server ./server
    - docker build -t 100121144d/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push 100121144d/multi-client
    - docker push 100121144d/multi-nginx
    - docker push 100121144d/multi-server
    - docker push 100121144d/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-3
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-3-508758267589
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY